export const SUCCESS_LOGIN = 'SUCCESS_LOGIN';
export const SUCCESS_LOGOUT = 'SUCCESS_LOGOUT';
export const SUCCESS_REFRESH = 'SUCCESS_REFRESH';
export const SUCCESS_SINGUP = 'SUCCESS_SINGUP';

export const FAIL_LOGIN = 'FAIL_LOGIN';
export const FAIL_LOGOUT = 'FAIL_LOGOUT';
export const FAIL_REFRESH = 'FAIL_REFRESH';
export const FAIL_SINGUP = 'FAIL_SINGUP';

export default {
  SUCCESS_LOGIN,
  SUCCESS_LOGOUT,
  SUCCESS_REFRESH,
  SUCCESS_SINGUP,
  FAIL_LOGIN,
  FAIL_LOGOUT,
  FAIL_REFRESH,
  FAIL_SINGUP
};
