export const SUCCESS_GET_USER_CLAIMS = 'SUCCESS_GET_USER_CLAIMS';
export const FAIL_GET_USER_CLAIMS = 'FAIL_GET_USER_CLAIMS';
export const SUCCESS_CREATE_USER_CLAIMS = 'SUCCESS_CREATE_USER_CLAIMS';
export const FAIL_CREATE_USER_CLAIMS = 'FAIL_CREATE_USER_CLAIMS';

export default {
  SUCCESS_GET_USER_CLAIMS,
  SUCCESS_CREATE_USER_CLAIMS,
  FAIL_GET_USER_CLAIMS,
  FAIL_CREATE_USER_CLAIMS
};
