export const SUCCESS_GET_USER_COMPUTER = 'SUCCESS_GET_USER_COMPUTER';
export const FAIL_GET_USER_COMPUTER = 'FAIL_GET_USER_COMPUTER';

export default {
  SUCCESS_GET_USER_COMPUTER,
  FAIL_GET_USER_COMPUTER
};
