export const SUCCESS_GET_USER_COMPUTER = 'SUCCESS_GET_USER_COMPUTER';
export const SUCCESS_GET_USER_COMPUTERS = 'SUCCESS_GET_USER_COMPUTERS';
export const FAIL_GET_USER_COMPUTER = 'FAIL_GET_USER_COMPUTER';
export const FAIL_GET_USER_COMPUTERS = 'FAIL_GET_USER_COMPUTERS';

export default {
  SUCCESS_GET_USER_COMPUTER,
  SUCCESS_GET_USER_COMPUTERS,
  FAIL_GET_USER_COMPUTER,
  FAIL_GET_USER_COMPUTERS
};
