export const SUCCESS_GET_USER_COMPUTER = 'SUCCESS_GET_USER_CLAIMS';
export const FAIL_GET_USER_COMPUTER = 'FAIL_GET_USER_CLAIMS';

export default {
  SUCCESS_GET_USER_COMPUTER,
  FAIL_GET_USER_COMPUTER
};
