export const SUCCESS_GET_USER_INFO = 'SUCCESS_GET_USER_INFO';
export const SUCCESS_PUT_USER_INFO = 'SUCCESS_PUT_USER_INFO';

export const FAIL_GET_USER_INFO = 'FAIL_GET_USER_INFO';
export const FAIL_PUT_USER_INFO = 'FAIL_PUT_USER_INFO';

export default {
  SUCCESS_GET_USER_INFO,
  FAIL_GET_USER_INFO,
  SUCCESS_PUT_USER_INFO,
  FAIL_PUT_USER_INFO
};
